// <auto-generated />
using LottoAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LottoAPI.Migrations
{
    [DbContext(typeof(LottoDbContext))]
    [Migration("20260208193916_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("LottoAPI.Domain.Entities.Lotto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastResultId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lottos");

                    b.HasData(
                        new
                        {
                            Id = "megasena",
                            Name = "Mega Sena"
                        },
                        new
                        {
                            Id = "lotofacil",
                            Name = "Loto Fácil"
                        },
                        new
                        {
                            Id = "quina",
                            Name = "Quina"
                        });
                });

            modelBuilder.Entity("LottoAPI.Domain.Entities.Result", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LottoId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Numbers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "LottoId");

                    b.HasIndex("LottoId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("LottoAPI.Domain.Entities.Result", b =>
                {
                    b.HasOne("LottoAPI.Domain.Entities.Lotto", "Lotto")
                        .WithMany()
                        .HasForeignKey("LottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lotto");
                });
#pragma warning restore 612, 618
        }
    }
}
